on: push
name: opensearch
jobs:
  opensearch:
    services:
      opensearch:
        image: opensearchproject/opensearch:2.13.0
        env:
          discovery.type: single-node
          plugins.security.disabled: "true"
          ES_JAVA_OPTS: "-Xms512m -Xmx512m"
          OPENSEARCH_INITIAL_ADMIN_PASSWORD: "${{ secrets.OPENSEARCH_PASSWORD }}"
        options: >-
          --health-cmd "curl http://localhost:9200/_cluster/health"
          --health-interval 10s 
          --health-timeout 5s
          --health-retries 10
    steps:
      - name: noop
        run: echo noop
